### ISSUE TITLE
Erreur Callback Xtense

### ISSUE THREAD

**Issue by darknoon29** [OGSteam/mod-recycleurs#8]
Arrive lorsque l'on n'a pas le vaisseau REC

``* CALL ERROR (recycleurs):
  Undefined array key "REC"
    Exception Stacktrace
      #0 D:\Wnmp\nginx-bins\default\www\ogspy\mod\recycleurs\_xtense.php(82): ogspy_error_handler(2, 'Undefined array...', 'D:\\Wnmp\\nginx-b...', 82)
      #1 D:\Wnmp\nginx-bins\default\www\ogspy\mod\recycleurs\_xtense.php(40): recycleurs_import(Array)
      #2 D:\Wnmp\nginx-bins\default\www\ogspy\mod\xtense\includes\CallbackHandler.php(53): recycleurs_Callback->recycleurs_import(Array)
      #3 D:\Wnmp\nginx-bins\default\www\ogspy\mod\xtense\xtense.php(1306): CallbackHandler->apply()
      #4 {main}

{"type":"home updated","page":"fleet","planet":"2:135:6","calls":{"success":["flottes"],"warning":[],"error":["Recycleurs"]},"call_messages":[{"mod":"Recycleurs","message":"Undefined array key \"REC\"","type":"error"}],"execution":"1.37"}``

**Comment by darknoon29** [comment]
Fix with 54f0d1d3e681642df4daf9e638ea748ea7a34d78
